# Generated by Django 4.0 on 2021-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishingDayPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('postText', models.TextField()),
                ('follow', models.BooleanField()),
                ('editDate', models.DateTimeField()),
                ('image', models.URLField()),
                ('youtube', models.URLField()),
                ('hashtag', models.TextField()),
                ('fishimage', models.URLField()),
                ('postLiked', models.BooleanField()),
                ('commented', models.BooleanField()),
                ('fishingCertification', models.BooleanField()),
                ('commentedUser', models.TextField()),
                ('likedUser', models.TextField()),
                ('viewerCount', models.IntegerField()),
                ('fishName', models.CharField(max_length=50)),
                ('fishSize', models.FloatField()),
                ('fishGeo', models.TextField()),
                ('fishingMethod', models.CharField(max_length=100)),
                ('fishingbait', models.CharField(max_length=100)),
                ('fishingDate', models.DateTimeField()),
            ],
        ),
    ]
