# Generated by Django 4.0 on 2021-12-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishingday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingdaypost',
            name='commentedUser',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='fishGeo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='fishName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='fishSize',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='fishimage',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='fishingCertification',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='fishingDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='fishingMethod',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='fishingbait',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='likedUser',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='postText',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fishingdaypost',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
