# Generated by Django 4.0 on 2021-12-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishingday', '0002_alter_fishingdaypost_commenteduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingdaypost',
            name='postText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
